group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


#Enable discovvery
discovery:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate



#circadian ligthing switch
input_boolean:
  circadian_lighting:
    name: Circadian Lighting
    icon: mdi:alarm-light
    
  test_switch:
    name: Test switch
    icon: mdi:alarm-light

# configure lights
light:
  - platform: group
    name: Hallway Chandelier
    entities:
    - light.hallway_chandelier1
    - light.hallway_chandelier2
    
  - platform: group    
    name: Kitchen Ceiling
    entities:
    - light.kitchen_ceiling1
    - light.kitchen_ceiling2
  
  - platform: group
    name: Workroom Ceiling
    entities:
    - light.workroom_ceiling_1
    - light.workroom_ceiling_2
    - light.workroom_ceiling_3

  - platform: group
    name: Bedroom Ceiling
    entities:
    - light.bedroom_ceiling_1
    - light.bedroom_ceiling_2
    - light.bedroom_ceiling_3
